import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/MainNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <MainNavigation />
        <main className="py-20 px-6 max-w-6xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
